<a href="https://colab.research.google.com/github/SeokcheonMoon/study_data_analytics/blob/main/docs/pandas/03_pandas_datetimes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 한글 폰트 설치
!apt-get install -y fonts-nanum
!fc-cache -fv
!rm ~/.cache/matplotlib -rf
# 설치 후 colab 경우 Reuntime > Restart session 필요

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [17]:
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import seaborn as sns
mpl.rc('font', family='NanumBarunGothic') # 혹은 다른 설치한 Nanum 폰트 사용

## datatime in Series

In [18]:
data = {
    "시작일": [
        "2019-01-07 08:56", "2019-02-05 09:30", "2019-03-10 11:00",
        "2019-04-12 10:15", "2019-05-19 12:42", "2019-06-21 13:53",
        "2019-07-28 14:08", "2019-08-15 15:22", "2019-09-18 16:33",
        "2019-10-23 17:44"
    ],
    "완료일_한글": [
        "2019-01-11 오후 05:32", "2019-02-09 오후 04:20", "2019-03-14 오후 06:45",
        "2019-04-16 오후 08:55", "2019-05-23 오후 07:30", "2019-06-25 오후 03:44",
        "2019-08-01 오후 04:16", "2019-08-19 오후 05:47", "2019-09-22 오후 06:00",
        "2019-10-27 오후 09:30"
    ],
    "신청일_수치": [
        20181227, 20190201, 20190306, 20190408, 20190515,
        20190617, 20190724, 20190811, 20190914, 20191019
    ],
    "신청일": [
        "2018.12.27", "2019.02.01", "2019.03.06", "2019.04.08", "2019.05.15",
        "2019.06.17", "2019.07.24", "2019.08.11", "2019.09.14", "2019.10.19"
    ]
}

In [19]:
df_datetimes = pd.DataFrame(data)
df_datetimes[:2]

                시작일               완료일_한글    신청일_수치         신청일
0  2019-01-07 08:56  2019-01-11 오후 05:32  20181227  2018.12.27
1  2019-02-05 09:30  2019-02-09 오후 04:20  20190201  2019.02.01

In [20]:
df_datetimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시작일     10 non-null     object
 1   완료일_한글  10 non-null     object
 2   신청일_수치  10 non-null     int64
 3   신청일     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 448.0+ bytes

In [21]:
df_datetimes.columns

Index(['시작일', '완료일_한글', '신청일_수치', '신청일'], dtype='object')

#### 문자열이 날짜 구성과 유사 ---> to_datetime()

In [24]:
df_datetimes["시작일_datetime"] = pd.to_datetime(df_datetimes["시작일"])
df_datetimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   시작일           10 non-null     object
 1   완료일_한글        10 non-null     object
 2   신청일_수치        10 non-null     int64
 3   신청일           10 non-null     object
 4   시작일_datetime  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 528.0+ bytes

#### 문자열(날짜 구성이 묘할때) -> to_datetime with formtatting datatype

In [29]:
pd.to_datetime(df_datetimes["신청일"])

0   2018-12-27
1   2019-02-01
2   2019-03-06
3   2019-04-08
4   2019-05-15
5   2019-06-17
6   2019-07-24
7   2019-08-11
8   2019-09-14
9   2019-10-19
Name: 신청일, dtype: datetime64[ns]

In [32]:
df_datetimes["신청일_datetime"] = pd.to_datetime(df_datetimes["신청일"],format="%Y.%m.%d")
df_datetimes.info()                                                                                   # 시작일 datetime 의 타입이 object에서 datetime으로 바뀜

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   시작일           10 non-null     object
 1   완료일_한글        10 non-null     object
 2   신청일_수치        10 non-null     int64
 3   신청일           10 non-null     object
 4   시작일_datetime  10 non-null     datetime64[ns]
 5   신청일_datetime  10 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 608.0+ bytes

#### 수치형

In [35]:
pd.to_datetime(df_datetimes["신청일_수치"])

0   1970-01-01 00:00:00.020181227
1   1970-01-01 00:00:00.020190201
2   1970-01-01 00:00:00.020190306
3   1970-01-01 00:00:00.020190408
4   1970-01-01 00:00:00.020190515
5   1970-01-01 00:00:00.020190617
6   1970-01-01 00:00:00.020190724
7   1970-01-01 00:00:00.020190811
8   1970-01-01 00:00:00.020190914
9   1970-01-01 00:00:00.020191019
Name: 신청일_수치, dtype: datetime64[ns]

In [40]:
df_datetimes["신청일_수치_datetime"] = pd.to_datetime(df_datetimes["신청일_수치"],format="%Y.%m.%d")

In [41]:
df_datetimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   시작일              10 non-null     object
 1   완료일_한글           10 non-null     object
 2   신청일_수치           10 non-null     int64
 3   신청일              10 non-null     object
 4   시작일_datetime     10 non-null     datetime64[ns]
 5   신청일_datetime     10 non-null     datetime64[ns]
 6   신청일_수치_datetime  10 non-null     datetime64[ns]
dtypes: datetime64[ns](3), int64(1), object(3)
memory usage: 688.0+ bytes

#### 날짜 간 연산

In [44]:
df_datetimes["착수일 간격"] = df_datetimes["신청일_datetime"] - df_datetimes["시작일_datetime"]

In [46]:
df_datetimes["착수일 간격"]

0   -12 days +15:04:00
1    -5 days +14:30:00
2    -5 days +13:00:00
3    -5 days +13:45:00
4    -5 days +11:18:00
5    -5 days +10:07:00
6    -5 days +09:52:00
7    -5 days +08:38:00
8    -5 days +07:27:00
9    -5 days +06:16:00
Name: 착수일 간격, dtype: timedelta64[ns]

In [48]:
df_datetimes.describe()

             신청일_수치                     착수일 간격
count  1.000000e+01                         10
mean   2.018967e+07          -6 days +18:11:42
std    2.979675e+03  2 days 03:45:54.370058767
min    2.018123e+07         -12 days +15:04:00
25%    2.019033e+07          -5 days +07:44:45
50%    2.019057e+07          -5 days +09:59:30
75%    2.019079e+07          -5 days +12:34:30
max    2.019102e+07          -5 days +14:30:00

In [52]:
df_datetimes.describe(include = ["datetime"],datetime_is_numeric=True)

              시작일_datetime         신청일_datetime                신청일_수치_datetime
count                   10                   10                             10
mean   2019-06-01 08:12:18  2019-05-27 02:24:00  1970-01-01 00:00:00.020189674
min    2019-01-07 08:56:00  2018-12-27 00:00:00  1970-01-01 00:00:00.020181227
25%    2019-03-18 16:48:45  2019-03-14 06:00:00  1970-01-01 00:00:00.020190331
50%    2019-06-05 01:17:30  2019-05-31 12:00:00  1970-01-01 00:00:00.020190566
75%    2019-08-11 03:03:30  2019-08-06 12:00:00  1970-01-01 00:00:00.020190789
max    2019-10-23 17:44:00  2019-10-19 00:00:00  1970-01-01 00:00:00.020191019

#### 시간 단위별 분해
- 년, 월, 일, 주, 분기

In [61]:
df_datetimes["신청일_datetime_year"] = df_datetimes["신청일_datetime"].dt.year
df_datetimes["신청일_datetime_year"]

0    2018
1    2019
2    2019
3    2019
4    2019
5    2019
6    2019
7    2019
8    2019
9    2019
Name: 신청일_datetime_year, dtype: int64

In [62]:
df_datetimes["신청일_datetime_month"] = df_datetimes["신청일_datetime"].dt.month
df_datetimes["신청일_datetime_month"]

0    12
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: 신청일_datetime_month, dtype: int64

In [64]:
df_datetimes["신청일_datetime_day"] = df_datetimes["신청일_datetime"].dt.day
df_datetimes["신청일_datetime_day"]

0    27
1     1
2     6
3     8
4    15
5    17
6    24
7    11
8    14
9    19
Name: 신청일_datetime_day, dtype: int64

In [66]:
df_datetimes["신청일_datetime_week"] = df_datetimes["신청일_datetime"].dt.isocalendar().week
df_datetimes["신청일_datetime_week"]

0    52
1     5
2    10
3    15
4    20
5    25
6    30
7    32
8    37
9    42
Name: 신청일_datetime_week, dtype: UInt32

In [72]:
df_datetimes["신청일_datetime_quarter"] = df_datetimes["신청일_datetime"].dt.quarter
df_datetimes["신청일_datetime_quarter"]

0    4
1    1
2    1
3    2
4    2
5    2
6    3
7    3
8    3
9    4
Name: 신청일_datetime_quarter, dtype: int64

In [69]:
df_datetimes[:10]

,시작일,완료일_한글,신청일_수치,신청일,시작일_datetime,신청일_datetime,신청일_수치_datetime,착수일 간격,신청일_datetime_month,신청일_datetime_year,신청일_datetime_day,신청일_datetime_week,신청일_datetime_quater
0,2019-01-07 08:56,2019-01-11 오후 05:32,20181227,2018.12.27,2019-01-07 08:56:00,2018-12-27,1970-01-01 00:00:00.020181227,-12 days +15:04:00,12,2018,27,52,4
1,2019-02-05 09:30,2019-02-09 오후 04:20,20190201,2019.02.01,2019-02-05 09:30:00,2019-02-01,1970-01-01 00:00:00.020190201,-5 days +14:30:00,2,2019,1,5,1
2,2019-03-10 11:00,2019-03-14 오후 06:45,20190306,2019.03.06,2019-03-10 11:00:00,2019-03-06,1970-01-01 00:00:00.020190306,-5 days +13:00:00,3,2019,6,10,1
3,2019-04-12 10:15,2019-04-16 오후 08:55,20190408,2019.04.08,2019-04-12 10:15:00,2019-04-08,1970-01-01 00:00:00.020190408,-5 days +13:45:00,4,2019,8,15,2
4,2019-05-19 12:42,2019-05-23 오후 07:30,20190515,2019.05.15,2019-05-19 12:42:00,2019-05-15,1970-01-01 00:00:00.020190515,-5 days +11:18:00,5,2019,15,20,2
5,2019-06-21 13:53,2019-06-25 오후 03:44,20190617,2019.06.17,2019-06-21 13:53:00,2019-06-17,1970-01-01 00:00:00.020190617,-5 days +10:07:00,6,2019,17,25,2
6,2019-07-28 14:08,2019-08-01 오후 04:16,20190724,2019.07.24,2019-07-28 14:08:00,2019-07-24,1970-01-01 00:00:00.020190724,-5 days +09:52:00,7,2019,24,30,3
7,2019-08-15 15:22,2019-08-19 오후 05:47,20190811,2019.08.11,2019-08-15 15:22:00,2019-08-11,1970-01-01 00:00:00.020190811,-5 days +08:38:00,8,2019,11,32,3
8,2019-09-18 16:33,2019-09-22 오후 06:00,20190914,2019.09.14,2019-09-18 16:33:00,2019-09-14,1970-01-01 00:00:00.020190914,-5 days +07:27:00,9,2019,14,37,3
9,2019-10-23 17:44,2019-10-27 오후 09:30,20191019,2019.10.19,2019-10-23 17:44:00,2019-10-19,1970-01-01 00:00:00.020191019,-5 days +06:16:00,10,2019,19,42,4

In [74]:
df_datetimes["신청일_datetime_quarter"].unique()

array([4, 1, 2, 3])

In [75]:
df_datetimes["신청일_datetime_quarter"].value_counts()

2    3
3    3
4    2
1    2
Name: 신청일_datetime_quarter, dtype: int64